version: '3.1'
services:
  products-services:
    image: products-services
    restart: always
    environment:
      SERVER_PORT: 80
    ports:
      - 8088:80
  order-services:
    image: order-services
    restart: always
    environment:
      SERVER_PORT: 80
    ports:
      - 8080:80
    links:
      - products-services
    depends_on:
      - products-services



